### ISSUE TITLE
Edit button doesn't work on Classes and Users

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/admin#13]
I was clicking "edit" on Classes and Users page but it's not responding.

**Comment by stevenolen** [comment]
This one is a little odd -- I actually can't recreate it.  I can get myself in a situation where clicking one of the edit buttons causes a few second delay before the screen changes, but never completely unresponsive.

You may also notice some delay in being able to click immediately upon visiting the page (esp with 'users' page on mtest) since the server call happening on the fly there is taking forever to return.

Could you see if the clicks are eventually registering like I mentioned, or if they really aren't an exact step-by-step used to get to that point (eg. from a full page refresh, what links were clicked, was the refresh icon spinning while doing those actions?). This is pretty low priority though, since the admin tool wont be user-facing.

Thank you!

**Comment by ctrance** [comment]
@stevenolen - It happens when you do a search first then clicking the edit button. In the class search for "test" then tap "Edit" button of Test Class. Then in the user search for "mwf.cathy" then tap "Edit" button for mwf.cathy.

**Comment by stevenolen** [comment]
@ctrance retest when you get a chance...should be fixed (note if you test with user the server call delays may slow you up a bit when jumping between the user detail and main user list pages!

**Comment by ctrance** [comment]
fixed now!
